// api/agent/contracts.draft.js — Tool: agent.contracts.draft  (Tier 2)
//
// Creates a contract DOCUMENT in Firestore, pre-compiled with everything
// Homie has gathered (from a converted lead, an intake form, etc).
// Status = 'draft' so the portal sees it but doesn't activate payments /
// signatures until the operator reviews and "promotes" it.
//
// The PDF (Allegato B for 'transitorio', Allegato C for 'studenti') is
// generated by portal.html the first time someone opens the contract —
// that code is already client-side (jsPDF + signature embedding) and
// re-porting it to Node would duplicate ~600 LOC. Acceptable trade-off
// because the operator typically opens the contract right after Homie
// drafts it (to review the canone, deposit, etc).
//
// Body: {
//   type:         'transitorio' | 'studenti'   required
//   propertyId:   string                       required
//   tenantId:     string                       required
//   startDate:    'YYYY-MM-DD'                 required
//   endDate?:     'YYYY-MM-DD'                 default: +18 months
//   rent:         number                       required (monthly EUR)
//   deposit?:     number                       default: 2 × rent
//   depositMonths?: number                     default: 2
//   accessoryCharges?: number                  default: 0
//   paymentDay?:  number                       default: 5
//   paymentMethod?: string                     default: 'bonifico'
//   cedolareSecca?: boolean                    default: true
//   transitionalReason?: string                (for type='transitorio')
//   studenti?:    { corsoStudi, universita, ... }  (for type='studenti')
//   cohabitants?: string
//   notes?:       string
//   linkedLeadId?: string
// }

import { fsCreate, fsGet, fsPatch, logActivity, guardPost, okJson, errJson } from './_lib.js';

const VALID_TYPES = new Set(['transitorio', 'studenti']);

function addMonths(dateStr, months) {
  const d = new Date(dateStr); d.setMonth(d.getMonth() + months);
  return d.toISOString().split('T')[0];
}

export default async function handler(req, res) {
  const body = await guardPost(req, res); if (!body) return;

  const errors = [];
  if (!VALID_TYPES.has(body.type)) errors.push('type must be transitorio | studenti');
  if (!body.propertyId) errors.push('propertyId required');
  if (!body.tenantId)   errors.push('tenantId required');
  if (!body.startDate || !/^\d{4}-\d{2}-\d{2}$/.test(body.startDate)) errors.push('startDate must be YYYY-MM-DD');
  if (typeof body.rent !== 'number' || body.rent <= 0) errors.push('rent must be a positive number');
  if (errors.length) return errJson(res, 400, 'validation', errors);

  // Quick existence checks for FKs (cheap and prevents silent orphans)
  const [property, tenant] = await Promise.all([
    fsGet(`properties/${body.propertyId}`),
    fsGet(`users/${body.tenantId}`),
  ]);
  if (!property) return errJson(res, 404, 'property_not_found');
  if (!tenant)   return errJson(res, 404, 'tenant_not_found');

  const endDate = body.endDate || addMonths(body.startDate, body.type === 'studenti' ? 12 : 18);
  const deposit = typeof body.deposit === 'number' ? body.deposit : body.rent * (body.depositMonths || 2);
  const depositMonths = body.depositMonths || Math.round(deposit / body.rent);
  const paymentDay = body.paymentDay || 5;
  const paymentMethod = body.paymentMethod || 'bonifico';
  const cedolareSecca = body.cedolareSecca !== false;

  const contract = {
    type: body.type,
    propertyId: body.propertyId, tenantId: body.tenantId,
    startDate: body.startDate, endDate,
    rent: body.rent, deposit, depositMonths,
    accessoryCharges: body.accessoryCharges || 0,
    paymentMethod, paymentDay, cedolareSecca,
    transitionalReason: body.transitionalReason || null,
    studenti: body.studenti || null,
    cohabitants: body.cohabitants || null,
    notes: body.notes || null,
    linkedLeadId: body.linkedLeadId || null,
    status: 'draft',          // <-- the portal recognises this and shows a "Promuovi → Attivo" CTA
    signatureStatus: 'none',
    landlordSignature: null, tenantSignature: null,
    createdBy: 'agent',
    createdAt: new Date(),
    // Structured canone block expected by the portal's math
    canone: {
      monthly: body.rent,
      total: body.rent * 12,
      installments: 12,
      paymentDay, paymentMethod,
      cedolareSecca,
      oneriMode: body.accessoryCharges ? 'separati' : 'inclusi',
    },
    durata: { startDate: body.startDate, endDate, text: `${body.startDate} → ${endDate}` },
  };

  try {
    const { id } = await fsCreate('contracts', contract);
    if (body.linkedLeadId) {
      await fsPatch(`leads/${body.linkedLeadId}`, { contractDraftId: id, status: 'converted', convertedAt: new Date() }).catch(() => {});
    }
    await logActivity('Contratto bozza (agent)', 'contract', { contractId: id, type: body.type, propertyId: body.propertyId, rent: body.rent });
    return okJson(res, { id, status: 'draft', endDate, deposit });
  } catch (e) { return errJson(res, 500, e.message); }
}
