// api/sign/_finalize.js
// Runs once a standard contract is FULLY signed (called server-side by
// api/sign/submit on completion). It:
//   1. generates the full post-signature obligations (fiscal + procedural —
//      see POST_SIGNATURE_OBLIGATIONS.md);
//   2. builds a tamper-evident FES signing certificate PDF (signatures + audit)
//      server-side and stores it on the contract;
//   3. issues the tenant magic link server-side (single-use, 72h);
//   4. sends branded tenant + landlord welcome emails (with the certificate).
// Idempotent via contract.finalizedAt.
//
// Note: the RLI registration deadline + monthly payments are created by
// api/sign/submit; finalize adds everything else.

import crypto from 'node:crypto';
import { fsCreate, fsPatch, fsGet, getAdminToken } from '../homie/_lib.js';
import { sendEmail } from '../agent/_lib.js';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const BASE = 'https://www.boomrome.com';
const GOLD = '#B8860B';
const STORAGE_BUCKET = process.env.FIREBASE_STORAGE_BUCKET || 'boom-property-dashboards.firebasestorage.app';
const MS_CONSENT = 'I confirm my identity and accept all lease terms. This digital signature is legally valid (FES — Art. 21 CAD).';

const EU_KEYS = ['ital','franc','german','tedesc','spagn','spain','portog','portug','paesi bassi','oland','netherl','dutch','belg','austri','irland','ireland','grec','greece','hellen','svez','swed','danim','denmark','danish','finland','finlandi','pol on','polon','polish','cech','czech','slovacch','slovak','sloven','ungher','hungar','magyar','romen','romania','romanian','bulgar','croat','eston','letton','latvia','lituan','lithuan','lussemburg','luxembourg','malt','cipr','cypr','norv','norway','island','iceland','liechtenstein','svizz','switzerl','swiss','europe'];
function isEU(nat){
  if(!nat) return false;
  const n = String(nat).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'').trim();
  if(!n) return false;
  return EU_KEYS.some(k => n.indexOf(k) !== -1);
}
const ymd = (d) => new Date(d).toISOString().split('T')[0];
const addDays = (base, n) => { const d = new Date(base); d.setDate(d.getDate() + n); return ymd(d); };
const money = (v) => (v == null || v === '') ? '' : '€' + Number(v).toLocaleString('it-IT');
const sha256 = (s) => crypto.createHash('sha256').update(String(s), 'utf8').digest('hex');

export async function finalizeContract(contract){
  if(!contract || !contract.id) return { ok:false, error:'no_contract' };
  if(contract.finalizedAt) return { ok:true, skipped:true };

  const now = new Date();
  const signDate = contract.fullySignedAt ? new Date(contract.fullySignedAt) : now;
  const start = contract.startDate ? new Date(contract.startDate) : signDate;

  const property = contract.propertyId ? await fsGet(`properties/${contract.propertyId}`).catch(()=>null) : null;
  const tenant   = contract.tenantId ? await fsGet(`users/${contract.tenantId}`).catch(()=>null) : null;
  const ownerId  = property && property.ownerId;
  const landlord = ownerId ? await fsGet(`users/${ownerId}`).catch(()=>null) : null;

  const cedolare = contract.cedolareSecca === true || contract.regime === 'cedolare';
  const nationality = contract.tenantNationality || (tenant && tenant.nationality) || '';
  const nonEU = !isEU(nationality);
  const propLabel = (property && (property.address || property.name)) || '';
  const linked = { linkedContractId: contract.id, linkedPropertyId: contract.propertyId || '' };

  // ── Obligations (RLI + payments are created by submit) ──
  const ob = [];
  const add = (title, opts) => ob.push(Object.assign({
    title, type: opts.type || 'obligation', date: opts.date,
    priority: opts.priority || 'medium', category: opts.category || 'fiscal',
    owner: opts.owner || 'admin', legalRef: opts.legalRef || '', notes: opts.notes || '',
    status: 'pending', autoGenerated: true, source: 'finalize', createdAt: now,
  }, linked));

  if (cedolare) {
    add('Cedolare: raccomandata/PEC al conduttore (rinuncia adeguamento ISTAT)', { type:'fiscal', date: addDays(signDate, 20), owner:'landlord', priority:'high', legalRef:'D.Lgs 23/2011 art.3', notes:'Obbligatoria per l’opzione cedolare secca.' });
  } else {
    add('Scelta regime fiscale: Cedolare secca vs Registro + Bollo', { type:'fiscal', date: addDays(signDate, 18), owner:'landlord', priority:'high', legalRef:'D.Lgs 23/2011 art.3' });
    add('Imposta di registro 2% del canone annuo (min €67) – F24 ELIDE', { type:'fiscal', date: addDays(signDate, 30), owner:'landlord', priority:'high', legalRef:'DPR 131/1986', notes:'Ripartibile 50/50 tra le parti.' });
    add('Imposta di bollo €16 (ogni 4 facciate/100 righe, per copia)', { type:'fiscal', date: addDays(signDate, 30), owner:'landlord', priority:'medium', legalRef:'DPR 642/1972' });
  }
  if (nonEU) {
    add('Comunicazione cessione di fabbricato alla Questura/P.S.', { type:'fiscal', date: addDays(start, 2), owner:'landlord', priority:'high', legalRef:'art.7 D.L. 59/1978', notes:'Dovuta entro 48h se il conduttore è extra‑UE — verificare la nazionalità.' });
  }
  add('Denuncia TARI (occupazione) al Comune', { type:'fiscal', date: addDays(start, 30), owner:'tenant', priority:'medium', notes:'Termine secondo regolamento comunale.' });
  add('Voltura / attivazione utenze (luce, gas, acqua)', { type:'procedural', date: addDays(start, 7), owner:'tenant', priority:'medium', category:'procedural' });
  add('Cambio residenza/domicilio – Anagrafe (se applicabile)', { type:'procedural', date: addDays(start, 20), owner:'tenant', priority:'low', category:'procedural', legalRef:'DPR 223/1989' });
  add('Dichiarazione redditi: canone da dichiarare (CU/Redditi PF)', { type:'fiscal', date: ymd(new Date(now.getFullYear()+1, 5, 30)), owner:'landlord', priority:'low' });
  add('Consegna chiavi + verbale di consegna e lettura contatori', { type:'procedural', date: ymd(start), owner:'admin', priority:'high', category:'procedural' });
  add(`Verifica APE allegato + deposito cauzionale incassato${contract.deposit?(' ('+money(contract.deposit)+')'):''}`, { type:'procedural', date: addDays(signDate, 3), owner:'admin', priority:'high', category:'procedural' });
  add('Inventario / stato dei luoghi firmato', { type:'procedural', date: ymd(start), owner:'admin', priority:'medium', category:'procedural' });

  // Write obligations in parallel (the admin token is already warm) to keep
  // the signer's wait short.
  const obResults = await Promise.allSettled(ob.map(o => fsCreate('deadlines', o)));
  let created = obResults.filter(r => r.status === 'fulfilled').length;
  obResults.forEach(r => { if (r.status === 'rejected') console.warn('[finalize] obligation failed:', r.reason && r.reason.message); });

  // ── FES signing certificate PDF (server-side, tamper-evident) ──
  let certUrl = '';
  try {
    const bytes = await buildCertificate(contract, property);
    certUrl = await uploadPdf(`contracts/${contract.id}/signing-certificate.pdf`, Buffer.from(bytes));
  } catch(e){ console.warn('[finalize] certificate failed:', e.message); }

  // ── Server-issued tenant magic link (single-use, 72h) ──
  let magicId = '';
  try {
    const exp = new Date(now.getTime() + 72*60*60*1000);
    const ml = await fsCreate('magicLinks', {
      contractId: contract.id, tenantId: contract.tenantId || '',
      tenantEmail: (tenant && tenant.email) || contract.tenantEmail || '',
      used: false, expiresAt: exp, issuedBy: 'finalize', createdAt: now,
    });
    magicId = ml.id;
  } catch(e){ console.warn('[finalize] magicLink failed:', e.message); }
  const portalLink = magicId ? `${BASE}/portal.html?postSign=1&magicToken=${magicId}` : `${BASE}/portal.html`;

  // ── Welcome emails ──
  const tenantEmail = (tenant && tenant.email) || contract.tenantEmail || '';
  const tenantName = (tenant && tenant.name) || contract.tenantName || 'there';
  const landlordEmail = (landlord && landlord.email) || contract.landlordEmail || '';
  const landlordName = (landlord && landlord.name) || contract.landlordName || 'there';
  const certLine = certUrl ? `<p style="margin:14px 0 0;font-size:13px"><a href="${esc(certUrl)}" style="color:${GOLD};text-decoration:none">⬇ Download your signing certificate (PDF)</a></p>` : '';

  if (tenantEmail) {
    try {
      await sendEmail({
        to: tenantEmail,
        subject: '🔑 Welcome home — your BOOM contract is active',
        html: emailShell('Welcome home', `
          <p style="margin:0 0 14px">Hi ${esc(tenantName)},</p>
          <p style="margin:0 0 18px">Your lease for <b>${esc(propLabel || 'your new home')}</b> is now <b style="color:${GOLD}">fully signed and active</b>. One tap and you’re in your portal — documents, payments and support in one place.</p>
          ${btn(portalLink, 'Enter my portal')}
          ${certLine}
          <p style="margin:18px 0 6px;font-size:13px;color:#666">Prefer a password? Open the portal above, then choose <b>“Set a password”</b> to make it permanent. This one‑tap link expires in 72 hours.</p>
          <div style="margin:22px 0 6px;border-top:1px solid #eee"></div>
          <p style="margin:16px 0 8px;font-size:13px;color:#666"><b>A couple of things on your side</b> (we’ll remind you):</p>
          <ul style="margin:0 0 4px;padding-left:18px;font-size:13px;color:#555;line-height:1.7">
            <li>Set up utilities (electricity, gas, water) around your move‑in</li>
            <li>TARI (waste tax) registration with the Comune</li>
            <li>Residence/domicile registration if you need it</li>
          </ul>
        `),
      });
    } catch(e){ console.warn('[finalize] tenant email failed:', e.message); }
  }

  if (landlordEmail) {
    const fiscalLines = (cedolare
      ? ['Cedolare secca: raccomandata/PEC al conduttore (rinuncia ISTAT)']
      : ['Decision: cedolare secca vs registro+bollo', 'Imposta di registro 2% (min €67) + bollo €16'])
      .concat(['Registrazione contratto (RLI) entro 30 giorni'])
      .concat(nonEU ? ['Cessione di fabbricato alla Questura entro 48h (conduttore extra‑UE)'] : []);
    try {
      await sendEmail({
        to: landlordEmail,
        subject: '✓ Your BOOM lease is signed — what’s next',
        html: emailShell('Lease signed', `
          <p style="margin:0 0 14px">Hi ${esc(landlordName)},</p>
          <p style="margin:0 0 18px">The lease for <b>${esc(propLabel || 'your property')}</b> is <b style="color:${GOLD}">fully signed</b>. BOOM has scheduled the deadlines below in your dashboard — we handle the registration with you.</p>
          <p style="margin:0 0 8px;font-size:13px;color:#666"><b>Upcoming fiscal steps</b></p>
          <ul style="margin:0 0 14px;padding-left:18px;font-size:13px;color:#555;line-height:1.7">${fiscalLines.map(l=>'<li>'+esc(l)+'</li>').join('')}</ul>
          ${btn(BASE+'/portal.html', 'Open dashboard')}
          ${certLine}
        `),
      });
    } catch(e){ console.warn('[finalize] landlord email failed:', e.message); }
  }

  try { await fsPatch(`contracts/${contract.id}`, { finalizedAt: now, magicLinkId: magicId, signingCertificateUrl: certUrl }); } catch(e){ console.warn('[finalize] mark failed:', e.message); }

  return { ok:true, obligations: created, certificate: !!certUrl, magicLink: !!magicId, tenantEmail: !!tenantEmail, landlordEmail: !!landlordEmail };
}

// ── Firebase Storage upload (admin token) ──
async function uploadPdf(path, bytes){
  const token = await getAdminToken();
  const url = `https://firebasestorage.googleapis.com/v0/b/${STORAGE_BUCKET}/o?uploadType=media&name=${encodeURIComponent(path)}`;
  const r = await fetch(url, { method:'POST', headers:{ Authorization:`Bearer ${token}`, 'Content-Type':'application/pdf' }, body: bytes });
  if (!r.ok) throw new Error('storage_' + r.status + ': ' + (await r.text()).slice(0,200));
  const meta = await r.json().catch(()=>({}));
  const dt = (meta.downloadTokens || '').split(',')[0];
  return `https://firebasestorage.googleapis.com/v0/b/${STORAGE_BUCKET}/o/${encodeURIComponent(path)}?alt=media${dt ? ('&token=' + dt) : ''}`;
}

// ── FES signing certificate (one A4 page, signatures + audit trail) ──
async function buildCertificate(c, property){
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const dark = rgb(0.05,0.05,0.06), gold = rgb(0.72,0.55,0.05), grey = rgb(0.42,0.42,0.45);
  const T = (t,x,y,sz,f,col)=>page.drawText(String(t==null?'':t),{x,y,size:sz,font:f||font,color:col||dark});

  page.drawRectangle({ x:0, y:792, width:595, height:50, color:dark });
  T('BOOM', 40, 810, 18, bold, rgb(1,1,1));
  T('ROMA', 96, 812, 10, font, rgb(0.91,0.78,0.41));
  T('Electronic Signature Certificate', 360, 818, 9, font, rgb(0.8,0.8,0.8));
  T('Attestazione di Firma Elettronica', 360, 805, 9, font, rgb(0.8,0.8,0.8));

  let y = 758;
  T('ATTESTAZIONE DI FIRMA — FES (Art. 21 CAD)', 40, y, 13, bold, gold);
  page.drawLine({ start:{x:40,y:y-8}, end:{x:555,y:y-8}, thickness:1, color:gold });
  y -= 30;
  const row = (label, val) => { T(label, 40, y, 9, bold, grey); T(val, 180, y, 10, font, dark); y -= 18; };
  row('Contratto', c.id || '');
  row('Immobile', (property && (property.address || property.name)) || '');
  row('Tipo', c.type === 'studenti' ? 'Per studenti' : 'Transitorio');
  row('Canone / Deposito', (money(c.rent) || '-') + '   /   ' + (money(c.deposit) || '-'));
  row('Periodo', (c.startDate ? ymd(c.startDate) : '-') + '   →   ' + (c.endDate ? ymd(c.endDate) : '-'));
  row('Stato', 'COMPLETO — ' + (c.fullySignedAt ? new Date(c.fullySignedAt).toLocaleString('it-IT') : ''));
  y -= 8;

  const block = async (title, name, cf, sig, at, ip, hash, x) => {
    let yy = y;
    T(title, x, yy, 10, bold, gold); yy -= 16;
    T('Firmatario: ' + (name || '-'), x, yy, 9); yy -= 13;
    T('Codice Fiscale: ' + (cf || '-'), x, yy, 9); yy -= 13;
    T('Data/ora: ' + (at ? new Date(at).toLocaleString('it-IT') : '-'), x, yy, 9); yy -= 13;
    T('IP: ' + (ip || '-'), x, yy, 9); yy -= 14;
    page.drawRectangle({ x, y: yy-58, width:230, height:56, borderColor:grey, borderWidth:0.5, color:rgb(0.99,0.99,0.98) });
    if (sig) {
      try {
        const m = /^data:image\/(png|jpe?g);base64,(.+)$/i.exec(sig);
        if (m) { const b = Buffer.from(m[2], 'base64'); const im = m[1].toLowerCase().startsWith('jp') ? await pdf.embedJpg(b) : await pdf.embedPng(b);
          const ar = im.width / im.height; let w = 200, h = w / ar; if (h > 46) { h = 46; w = h * ar; }
          page.drawImage(im, { x: x + (230 - w)/2, y: yy - 56 + (52 - h)/2, width: w, height: h }); }
      } catch(e){}
    }
    yy -= 70;
    T('Consent hash: ' + String(hash || '').slice(0, 40), x, yy, 7, font, grey);
  };
  await block('CONDUTTORE (Tenant)', c.tenantName, c.tenantCF, c.tenantSignature, c.tenantSignedAt, c.tenantSignedIP, c.tenantConsentHash, 40);
  await block('LOCATORE (Landlord)', c.landlordName, c.landlordCF, c.landlordSignature, c.landlordSignedAt, c.landlordSignedIP, c.landlordConsentHash, 320);

  const docHash = sha256([c.id, c.rent, c.startDate, c.endDate, c.tenantSignedAt, c.landlordSignedAt, c.tenantConsentHash, c.landlordConsentHash].join('|'));
  page.drawLine({ start:{x:40,y:132}, end:{x:555,y:132}, thickness:0.5, color:grey });
  T('Document hash (SHA-256): ' + docHash, 40, 118, 7, font, grey);
  T('Consenso accettato: ' + MS_CONSENT, 40, 104, 7, font, grey);
  T('Firma Elettronica Semplice ai sensi dell’art. 21 D.Lgs 82/2005 (CAD) — BOOM Rome · boomrome.com', 40, 66, 8, font, grey);
  T('Generato il ' + new Date().toLocaleString('it-IT'), 40, 52, 7, font, grey);
  return await pdf.save();
}

// ── email helpers (inline styles for client compatibility) ──
function esc(s){ return String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
function btn(href, label){
  return `<a href="${esc(href)}" style="display:inline-block;background:linear-gradient(180deg,#F6E4A6,#E9C766 46%,#B98E2E);color:#1c1503;text-decoration:none;font-weight:700;font-size:14px;letter-spacing:.3px;padding:13px 26px;border-radius:11px">${esc(label)}</a>`;
}
function emailShell(title, inner){
  return `<div style="margin:0;padding:24px;background:#0c0c0e;font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif">
    <div style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:18px;overflow:hidden;box-shadow:0 14px 40px rgba(0,0,0,.4)">
      <div style="background:#0c0c0e;padding:22px 28px;text-align:center">
        <div style="font-size:18px;font-weight:300;letter-spacing:9px;color:#fff;padding-left:9px">BOOM</div>
        <div style="font-size:9px;letter-spacing:3px;text-transform:uppercase;color:#B8860B;margin-top:5px">${esc(title)}</div>
      </div>
      <div style="padding:28px 28px 30px;color:#222;font-size:15px;line-height:1.6">${inner}</div>
      <div style="padding:16px 28px;background:#f6f6f4;color:#999;font-size:11px;text-align:center">BOOM Rome · boomrome.com · Encrypted · FES (Art. 21 CAD)</div>
    </div>
  </div>`;
}
