import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fixture } from './fixture.mjs';
const require=createRequire(import.meta.url), UI=require('../../js/property-dossier.js');
let n=0;function test(label,fn){fn();n++;console.log('✓ '+label);}
const render=(state=fixture,tab='overview',source)=>UI.render(state,{id:'casa-demo',tab},source);
test('links encode ids and refuse malformed paths or unsupported sections',()=>{const id='casa ?#&é';assert.equal(UI.parseRoute(UI.routeFor(id,'documents')).id,id);for(const route of ['property/','property/%GG','property/a/nope','property/a/overview/extra','property/%2F/overview'])assert(UI.parseRoute(route).invalid);assert.equal(UI.parseRoute('innesto=ref'),null);assert.equal(UI.parseRoute('payments'),null);});
test('all record text is escaped and links reject executable URLs',()=>{const s=structuredClone(fixture);s.properties[0].name='<img src=x onerror=alert(1)>';s.properties[0].notes='<script>bad()</script>';s.properties[0].youtubeUrl='javascript:alert(1)';s.documents[0].fileUrl='data:text/html,bad';s.documents[0].name='<iframe src=x>';assert(!render(s).includes('<img src=x'));assert(!render(s).includes('<script>'));assert(!render(s).includes('javascript:'));assert(!render(s,'documents').includes('<iframe'));assert(!render(s,'documents').includes('data:text/html'));for(const url of ['//example.org','javascript:alert(1)','data:text/plain,a','https://user:secret@example.org'])assert.equal(UI.safeURL(url),'');});
test('unknown availability, zero floor/deposit and legacy rent remain honest',()=>{const s=structuredClone(fixture);delete s.properties[0].availabilityStatus;s.contracts[0].deposit=0;delete s.contracts[0].rent;s.contracts[0].canone={monthly:1400};assert(render(s).includes('Disponibilità da verificare'));assert(render(s).includes('<dt>Piano</dt><dd>0</dd>'));assert(/1[. ]?400,00/.test(render(s,'contracts')));assert(render(s,'contracts').includes('0,00'));});
test('recorded paidAt is visible; reported payment never appears paid',()=>{const h=render(fixture,'rent');assert(h.includes('3 ago 2026'));assert(h.includes('Segnalato · da verificare'));assert(h.includes('Canoni per il proprietario'));});
test('a deposit overdue is never introduced as a rent arrear',()=>{const s=structuredClone(fixture);s.payments=[{...s.payments[0],id:'deposit',type:'deposit-balance',status:'pending',dueDate:'2000-01-01'}];assert(render(s).includes('Un addebito in ritardo'));assert(!render(s).includes('Un canone in ritardo'));});
test('inconsistent references are reviewed before payment action',()=>{const s=structuredClone(fixture);s.contracts.push({id:'other',propertyId:'casa-vuota'});s.payments[1].contractId='other';const h=render(s);assert(h.includes('Collegamenti discordanti'));assert(h.includes('data-pdos-action="issues"'));});
test('legacy resolvedAt does not present an open job as resolved',()=>{const s=structuredClone(fixture);s.maintenance[0].resolvedAt='2026-09-19';const h=render(s,'activity');assert(!h.includes('Risoluzione registrata'));assert(!h.includes('Manutenzione risolta'));});
test('read errors and capped snapshots never imply complete fresh data',()=>{assert(render(fixture,'overview',{status:'error'}).includes('Aggiornamento non riuscito'));assert(render(fixture,'overview',{status:'ready',counts:{properties:400}}).includes('Archivio parziale'));assert(render(fixture,'overview',{status:'loading'}).includes('disabled'));});
test('non-admin cannot render names, contracts, files or balances',()=>{for(const role of ['landlord','tenant','owner','unknown']){const s={...fixture,profile:{role}};const h=render(s);assert(h.includes('Accesso riservato'));assert(!h.includes('Casa Aurora'));assert(!h.includes('Conduttore Demo'));}});
console.log(`${n} real-renderer checks passed.`);
