// api/generate-pass.js
// BOOM PropPass V2 — 5 distinct passes mapped to optimal Apple Wallet types.
//
//   Tenant Black     storeCard
//   Tenant Silver    storeCard   (only when tenant.isPremium === true)
//   Landlord         storeCard   (gold-amex)
//   Viewing          eventTicket (relevantDate + locations geo-fence — CRITICAL)
//   Referral         coupon      (voided lifecycle, expirationDate)
//
// All builders set: relevantDate (where applicable), locations, expirationDate,
// userInfo (analytics), barcodes (QR with `BOOM:{TYPE}:{id}`), webServiceURL placeholder.
//
// Asset path: assets/passes/{type}/{icon,logo,strip,thumbnail}{,@2x,@3x}.png
// (60 PNGs generated by scripts/generate-pass-assets.py — V3 brushed metal).

import { PKPass } from "passkit-generator";
import crypto from "crypto";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { fsPatch } from "./homie/_lib.js";

// ESM doesn't have __dirname; derive it
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const signerCert = Buffer.from(process.env.PASS_CERT_BASE64 || "", "base64");
const signerKey = Buffer.from(process.env.PASS_KEY_BASE64 || "", "base64");
const signerKeyPassphrase = process.env.PASS_KEY_PASSPHRASE || "";

// Apple WWDR G4 certificate (public, required by passkit-generator v3)
const wwdr = `-----BEGIN CERTIFICATE-----
MIIEVTCCAz2gAwIBAgIUE9x3lVJx5T3GMujM/+Uh88zFztIwDQYJKoZIhvcNAQEL
BQAwYjELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xJjAkBgNVBAsT
HUFwcGxlIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MRYwFAYDVQQDEw1BcHBsZSBS
b290IENBMB4XDTIwMTIxNjE5MzYwNFoXDTMwMTIxMDAwMDAwMFowdTFEMEIGA1UE
Aww7QXBwbGUgV29ybGR3aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNh
dGlvbiBBdXRob3JpdHkxCzAJBgNVBAsMAkc0MRMwEQYDVQQKDApBcHBsZSBJbmMu
MQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANAf
eKp6JzKwRl/nF3bYoJ0OKY6tPTKlxGs3yeRBkWq3eXFdDDQEYHX3rkOPR8SGHgjo
v9Y5Ui8eZ/xx8YJtPH4GUnadLLzVQ+mxtLxAOnhRXVGhJeG+bJGdayFZGEHVD41t
QSo5SiHgkJ9OE0/QjJoyuNdqkh4laqQyziIZhQVg3AJK8lrrd3kCfcCXVGySjnYB
5kaP5eYq+6KwrRitbTOFOCOL6oqW7Z+uZk+jDEAnbZXQYojZQykn/e2kv1MukBVl
PNkuYmQzHWxq3Y4hqqRfFcYw7V/mjDaSlLfcOQIA+2SM1AyB8j/VNJeHdSbCb64D
YyEMe9QbsWLFApy9/a8CAwEAAaOB7zCB7DASBgNVHRMBAf8ECDAGAQH/AgEAMB8G
A1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwheMEQGCCsGAQUFBwEBBDgwNjA0
BggrBgEFBQcwAYYoaHR0cDovL29jc3AuYXBwbGUuY29tL29jc3AwMy1hcHBsZXJv
b3RjYTAuBgNVHR8EJzAlMCOgIaAfhh1odHRwOi8vY3JsLmFwcGxlLmNvbS9yb290
LmNybDAdBgNVHQ4EFgQUW9n6HeeaGgujmXYiUIY+kchbd6gwDgYDVR0PAQH/BAQD
AgEGMBAGCiqGSIb3Y2QGAgEEAgUAMA0GCSqGSIb3DQEBCwUAA4IBAQA/Vj2e5bbD
eeZFIGi9v3OLLBKeAuOugCKMBB7DUshwgKj7zqew1UJEggOCTwb8O0kU+9h0UoWv
p50h5wESA5/NQFjQAde/MoMrU1goPO6cn1R2PWQnxn6NHThNLa6B5rmluJyJlPef
x4elUWY0GzlxOSTjh2fvpbFoe4zuPfeutnvi0v/fYcZqdUmVIkSoBPyUuAsuORFJ
EtHlgepZAE9bPFo22noicwkJac3AfOriJP6YRLj477JxPxpd1F1+M02cHSS+APCQ
A1iZQT0xWmJArzmoUUOSqwSonMJNsUvSq3xKX+udO7xPiEAGE/+QF4oIRynoYpgp
pU8RBWk6z/Kf
-----END CERTIFICATE-----`;

const PASS_TYPE_ID = "pass.com.boomrome.proppass";
const TEAM_ID = "3MFCAL4947";
const WEB_SERVICE_URL = "https://boomrome.com/api/pass-update";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function pad(n) { return String(n).padStart(2, "0"); }

function generateAuthToken(id) {
  return crypto
    .createHash("sha256")
    .update(`boom-${id}-${process.env.PASS_AUTH_SECRET || "fallback"}`)
    .digest("hex")
    .slice(0, 32);
}

function safeDate(input) {
  if (!input) return null;
  const d = input instanceof Date ? input : new Date(input);
  return isNaN(d.getTime()) ? null : d;
}

function formatDateRange(start, end) {
  const s = safeDate(start);
  const e = safeDate(end);
  if (!s || !e) return "";
  return `${pad(s.getDate())}/${pad(s.getMonth() + 1)} → ${pad(e.getDate())}/${pad(e.getMonth() + 1)}`;
}

function formatDate(d) {
  const dt = safeDate(d);
  if (!dt) return "";
  return `${pad(dt.getDate())}/${pad(dt.getMonth() + 1)}/${dt.getFullYear()}`;
}

function formatDateShort(d) {
  const dt = safeDate(d);
  if (!dt) return "";
  const days = ["DOM", "LUN", "MAR", "MER", "GIO", "VEN", "SAB"];
  const months = ["GEN", "FEB", "MAR", "APR", "MAG", "GIU", "LUG", "AGO", "SET", "OTT", "NOV", "DIC"];
  return `${days[dt.getDay()]} ${pad(dt.getDate())} ${months[dt.getMonth()]}`;
}

function formatTimeHHMM(d) {
  const dt = safeDate(d);
  if (!dt) return "";
  return `${pad(dt.getHours())}:${pad(dt.getMinutes())}`;
}

function loadAssets(type) {
  // assets/passes/{type}/ — produced by scripts/generate-pass-assets.py
  const baseDir = path.resolve(__dirname, "..", "assets", "passes", type);
  const files = [
    "icon.png", "icon@2x.png", "icon@3x.png",
    "logo.png", "logo@2x.png", "logo@3x.png",
    "strip.png", "strip@2x.png", "strip@3x.png",
    "thumbnail.png", "thumbnail@2x.png", "thumbnail@3x.png",
  ];
  const buffers = {};
  for (const f of files) {
    const fpath = path.join(baseDir, f);
    try {
      if (fs.existsSync(fpath)) buffers[f] = fs.readFileSync(fpath);
    } catch (e) { /* skip missing */ }
  }
  return buffers;
}

// ---------------------------------------------------------------------------
// Builders
// ---------------------------------------------------------------------------
function buildTenantPass({
  contractId,
  tenantName = "",
  propertyAddress = "",
  propertyCity = "Roma",
  propertyCoords = null,
  contractStart,
  contractEnd,
  monthlyRent,
  nextPaymentDate,
}) {
  const pass = {
    formatVersion: 1,
    passTypeIdentifier: PASS_TYPE_ID,
    teamIdentifier: TEAM_ID,
    organizationName: "BOOM Rome",
    description: `BOOM Tenant Card — ${tenantName}`,
    serialNumber: `tenant-${contractId || crypto.randomUUID()}`,
    backgroundColor: "rgb(8,8,10)",
    foregroundColor: "rgb(245,245,240)",
    labelColor: "rgb(212,175,55)",
    logoText: "BOOM",
    webServiceURL: WEB_SERVICE_URL,
    authenticationToken: generateAuthToken(contractId || tenantName),
    storeCard: {
      headerFields: [{ key: "type", label: "BOOM", value: "TENANT" }],
      primaryFields: [{ key: "name", label: "INQUILINO", value: tenantName }],
      secondaryFields: [
        { key: "address", label: "INDIRIZZO", value: propertyAddress },
        { key: "contract", label: "CONTRATTO", value: formatDateRange(contractStart, contractEnd) },
      ],
      auxiliaryFields: [
        { key: "rent", label: "CANONE", value: monthlyRent ? `€${monthlyRent}/MESE` : "" },
        { key: "next_payment", label: "PROSSIMA RATA", value: formatDate(nextPaymentDate) },
      ],
      backFields: [
        { key: "contract_id", label: "Contract ID", value: contractId || "" },
        { key: "support", label: "Support", value: "valentino@boom-rome.com\n+39 331 3251961" },
        { key: "terms", label: "Terms", value: "See contract for full terms." },
      ],
    },
    barcodes: [{
      format: "PKBarcodeFormatQR",
      message: `BOOM:TENANT:${contractId}`,
      messageEncoding: "iso-8859-1",
      altText: String(contractId || "").slice(0, 8).toUpperCase(),
    }],
    userInfo: { contractId, type: "tenant" },
  };
  if (propertyCoords && propertyCoords.lat && propertyCoords.lng) {
    pass.locations = [{
      latitude: parseFloat(propertyCoords.lat),
      longitude: parseFloat(propertyCoords.lng),
      relevantText: `Welcome home, ${(tenantName || "").split(" ")[0]}`,
    }];
  }
  const exp = safeDate(contractEnd);
  if (exp) pass.expirationDate = exp.toISOString();
  return pass;
}

function buildSilverPass(data) {
  const base = buildTenantPass(data);
  return {
    ...base,
    description: `BOOM Tenant Silver VIP — ${data.tenantName || ""}`,
    serialNumber: `silver-${data.contractId || crypto.randomUUID()}`,
    backgroundColor: "rgb(170,170,175)",
    foregroundColor: "rgb(20,20,25)",
    labelColor: "rgb(80,80,90)",
    storeCard: {
      ...base.storeCard,
      headerFields: [{ key: "type", label: "BOOM", value: "SILVER" }],
      auxiliaryFields: [
        ...base.storeCard.auxiliaryFields,
        { key: "status", label: "STATUS", value: "VIP" },
      ],
    },
    userInfo: { ...(base.userInfo || {}), type: "silver", tier: "VIP" },
  };
}

function buildLandlordPass({
  landlordId,
  landlordName = "",
  memberSince,
  propertiesCount = 0,
  totalRevenue = 0,
  partnerId,
  propertiesCoords = [],
}) {
  const pass = {
    formatVersion: 1,
    passTypeIdentifier: PASS_TYPE_ID,
    teamIdentifier: TEAM_ID,
    organizationName: "BOOM Rome",
    description: `BOOM Partner — ${landlordName}`,
    serialNumber: `landlord-${landlordId || crypto.randomUUID()}`,
    backgroundColor: "rgb(186,153,100)",
    foregroundColor: "rgb(0,0,0)",
    labelColor: "rgb(93,74,31)",
    logoText: "BOOM",
    webServiceURL: WEB_SERVICE_URL,
    authenticationToken: generateAuthToken(landlordId || landlordName),
    storeCard: {
      headerFields: [{
        key: "member",
        label: "MEMBER SINCE",
        value: String(memberSince || new Date().getFullYear()),
      }],
      primaryFields: [{ key: "name", label: "BOOM PARTNER", value: landlordName }],
      secondaryFields: [
        { key: "props", label: "PROPRIETÀ", value: `${propertiesCount} ATTIVE` },
        { key: "status", label: "STATUS", value: "PREMIUM" },
      ],
      auxiliaryFields: [
        { key: "revenue", label: "REVENUE", value: `€${totalRevenue || 0}` },
        { key: "partner_id", label: "BOOM ID", value: partnerId || "" },
      ],
      backFields: [
        { key: "support", label: "BOOM Support", value: "valentino@boom-rome.com\n+39 331 3251961" },
        { key: "dashboard", label: "Dashboard", value: "https://boomrome.com/portal.html" },
      ],
    },
    barcodes: [{
      format: "PKBarcodeFormatQR",
      message: `BOOM:LANDLORD:${landlordId}`,
      messageEncoding: "iso-8859-1",
      altText: String(landlordId || "").slice(0, 8).toUpperCase(),
    }],
    userInfo: { landlordId, type: "landlord", tier: "GOLD" },
  };
  if (Array.isArray(propertiesCoords) && propertiesCoords.length > 0) {
    pass.locations = propertiesCoords
      .filter((c) => c && c.lat && c.lng)
      .map((c, i) => ({
        latitude: parseFloat(c.lat),
        longitude: parseFloat(c.lng),
        relevantText: `Your property ${i + 1} of ${propertiesCoords.length}`,
      }));
  }
  return pass;
}

function buildViewingPass({
  viewingId,
  clientName = "",
  propertyAddress = "",
  propertyCity = "Roma",
  propertyCoords = null,
  confirmedDateISO,
  durationMinutes = 30,
  meetingPoint = "AL CITOFONO",
  isVoided = false,
}) {
  const eventDate = safeDate(confirmedDateISO);
  const expirationDate = eventDate
    ? new Date(eventDate.getTime() + (durationMinutes + 60) * 60 * 1000)
    : null;
  const formattedDate = formatDateShort(eventDate);
  const formattedTime = formatTimeHHMM(eventDate);

  const pass = {
    formatVersion: 1,
    passTypeIdentifier: PASS_TYPE_ID,
    teamIdentifier: TEAM_ID,
    organizationName: "BOOM Rome",
    description: `BOOM Viewing — ${propertyAddress}${formattedDate ? " on " + formattedDate : ""}${isVoided ? " (cancelled)" : ""}`,
    serialNumber: `viewing-${viewingId || crypto.randomUUID()}`,
    backgroundColor: "rgb(8,8,10)",
    foregroundColor: "rgb(245,245,240)",
    labelColor: "rgb(212,175,55)",
    logoText: "BOOM",
    webServiceURL: WEB_SERVICE_URL,
    authenticationToken: generateAuthToken(viewingId || clientName),
    eventTicket: {
      headerFields: [{ key: "type", label: "VIEWING", value: isVoided ? "CANCELLED" : "PRIVATE" }],
      primaryFields: [{ key: "address", label: "INDIRIZZO", value: propertyAddress }],
      secondaryFields: [
        { key: "date", label: "DATA", value: formattedDate || "TBD" },
        { key: "time", label: "ORA", value: formattedTime || "TBD" },
      ],
      auxiliaryFields: [
        { key: "duration", label: "DURATA", value: `${durationMinutes} MIN` },
        { key: "meeting", label: "MEETING POINT", value: meetingPoint },
      ],
      backFields: [
        { key: "client", label: "Client", value: clientName },
        { key: "cancellation", label: "Cancellation", value: isVoided ? "This viewing has been CANCELLED. Contact +39 331 3251961 to reschedule." : "Reschedule up to 2h before. Reply to confirmation email." },
        { key: "support", label: "Support", value: "valentino@boom-rome.com\n+39 331 3251961" },
      ],
    },
    voided: !!isVoided,
    barcodes: [{
      format: "PKBarcodeFormatQR",
      message: `BOOM:VIEWING:${viewingId}`,
      messageEncoding: "iso-8859-1",
      altText: String(viewingId || "").slice(0, 8).toUpperCase(),
    }],
    userInfo: { viewingId, type: "viewing", confirmedDate: confirmedDateISO || null, voided: !!isVoided },
  };
  // CRITICAL native features
  if (eventDate) pass.relevantDate = eventDate.toISOString();
  if (expirationDate) pass.expirationDate = expirationDate.toISOString();
  if (propertyCoords && propertyCoords.lat && propertyCoords.lng && !isVoided) {
    pass.locations = [{
      latitude: parseFloat(propertyCoords.lat),
      longitude: parseFloat(propertyCoords.lng),
      relevantText: `Welcome to your viewing — ${propertyAddress}`,
    }];
  }
  return pass;
}

function buildReferralPass({
  referrerId,
  referrerName = "",
  referralCode = "BOOM-" + crypto.randomBytes(3).toString("hex").toUpperCase(),
  memberSince,
  referralsActive = 0,
  totalEarned = 0,
  nextThreshold = "5 → €1.000",
  programEndDate = null,
  isVoided = false,
}) {
  const pass = {
    formatVersion: 1,
    passTypeIdentifier: PASS_TYPE_ID,
    teamIdentifier: TEAM_ID,
    organizationName: "BOOM Rome",
    description: `BOOM Circle — ${referrerName}`,
    serialNumber: `referral-${referrerId || referralCode}`,
    backgroundColor: "rgb(8,8,10)",
    foregroundColor: "rgb(201,169,110)",
    labelColor: "rgb(245,245,240)",
    logoText: "BOOM CIRCLE",
    webServiceURL: WEB_SERVICE_URL,
    authenticationToken: generateAuthToken(referrerId || referralCode),
    coupon: {
      headerFields: [{ key: "type", label: "BOOM", value: "CIRCLE" }],
      primaryFields: [{
        key: "name",
        label: `MEMBRO DAL ${memberSince || new Date().getFullYear()}`,
        value: referrerName,
      }],
      secondaryFields: [
        { key: "active", label: "REFERRAL", value: `${referralsActive} ATTIVI` },
        { key: "earned", label: "EARNED", value: `€${totalEarned}` },
      ],
      auxiliaryFields: [
        { key: "threshold", label: "PROSSIMA SOGLIA", value: nextThreshold },
        { key: "code", label: "CODE", value: referralCode },
      ],
      backFields: [
        { key: "how", label: "How it works", value: "Share your code with friends. When they sign a contract with BOOM, you earn €150 credit. Cumulative." },
        { key: "share", label: "Share link", value: `https://boomrome.com/?ref=${referralCode}` },
        { key: "support", label: "Support", value: "valentino@boom-rome.com\n+39 331 3251961" },
      ],
    },
    voided: !!isVoided,
    barcodes: [{
      format: "PKBarcodeFormatQR",
      message: `BOOM:REFERRAL:${referralCode}`,
      messageEncoding: "iso-8859-1",
      altText: referralCode,
    }],
    userInfo: { referrerId, type: "referral", referralCode },
  };
  const exp = safeDate(programEndDate);
  if (exp) pass.expirationDate = exp.toISOString();
  return pass;
}

const BUILDERS = {
  tenant: buildTenantPass,
  silver: buildSilverPass,
  landlord: buildLandlordPass,
  viewing: buildViewingPass,
  referral: buildReferralPass,
};

// Export builders for unit-test / mock generation outside the handler
export { BUILDERS, loadAssets, generateAuthToken, PASS_TYPE_ID, TEAM_ID, WEB_SERVICE_URL };

// Build + sign a .pkpass for {type, data}. Returns { buffer, passJson }.
// Shared by the HTTP handler, the Pass Studio (pass-issue) and the PassKit
// web service (pass-update get-latest), so signing logic lives in one place.
export function buildAndSign(type, data) {
  const builder = BUILDERS[type];
  if (!builder) throw new Error("Unknown pass type: " + type);
  const passJson = builder(data || {});
  const assets = loadAssets(type);
  assets["pass.json"] = Buffer.from(JSON.stringify(passJson));
  const pass = new PKPass(assets, { signerCert, signerKey, signerKeyPassphrase, wwdr });
  return { buffer: pass.getAsBuffer(), passJson };
}

// ---------------------------------------------------------------------------
// HTTP handler
// ---------------------------------------------------------------------------
export default async function handler(req, res) {
  const allowedOrigins = ["https://boomrome.com", "https://www.boomrome.com"];
  const origin = req.headers.origin;
  if (allowedOrigins.includes(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
  }
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  if (req.method === "OPTIONS") return res.status(200).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  try {
    const { type = "tenant", data } = req.body || {};
    if (!data) return res.status(400).json({ error: "Missing data" });
    const builder = BUILDERS[type];
    if (!builder) return res.status(400).json({ error: "Unknown type: " + type });

    const { buffer: buf, passJson } = buildAndSign(type, data);

    // Track the pass so the web service knows it exists and can push updates.
    try {
      const serial = passJson.serialNumber;
      const entityId = String(serial).split("-").slice(1).join("-");
      await fsPatch(`passMeta/${serial}`, {
        type, entityId, serial,
        updatedAt: new Date(), lastBuiltAt: new Date(),
      });
    } catch (e) { /* non-fatal: tracking is best-effort */ }

    res.setHeader("Content-Type", "application/vnd.apple.pkpass");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=boom-${type}-${passJson.serialNumber.slice(-12)}.pkpass`
    );
    return res.send(buf);
  } catch (err) {
    console.error("PropPass error:", err);
    return res.status(500).json({ error: "Failed to generate pass", detail: err.message });
  }
}
